### ISSUE TITLE
DCEG - Main Navigation is no longer sticky

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2316]
When scrolling down the page anywhere within https://dceg.cancer.gov/, the main navigation is no longer sticking to the top of the page. The primary navigation bar should stick to the top. Screenshot below shows it's not sticking once you scroll past it:

<img width="1680" alt="Screen Shot 2019-08-09 at 4 20 48 PM" src="https://user-images.githubusercontent.com/29731392/62806792-c189d180-bac1-11e9-96b7-4ae7de4c77ee.png">

**Comment by amydugan** [comment]
@arcepaul @markecramer - I am taking this ticket out of Digital Platform Release 1.1.5 since this is being addressed in DTM.

**Comment by markecramer** [comment]
The root of the problem is that linkback, v1, is not a universal solution. It requires a lot of customization site to site. The linkback was taken directly from the old DCEG and since the new DCEG does not exactly match the old DCEG in functionality, some of the customization needs to be updated.

Solution: Since this is a microsite like MyPart, NCI Connect and Nano, it should be using the same code for the linkback. I've gone into Adobe Tag Manager (DTM) where linkback exists and modified the linkback rules for DCEG to be the same as the other 3 microsites.

* Note - the other 3 microsites have an issue with linkback obscuring part of the sticky nav. This fix DOES NOT address that issue. There will need to be a separate ticket to look into that issue once we resolve the other linkback issues first.

Testing Instructions: This is a DTM fix. For any changes to DTM that are not approved to publish, they must be tested using a Chrome plugin called Launch and DTM Switch. To install in Chrome, 

1. go to https://chrome.google.com/webstore/detail/launch-and-dtm-switch/nlgdemkdapolikbjimjajpmonpbpmipk?hl=en and hit the Install button.

2. this should give you an icon to the right of your URL bar that looks like the Rocket icon on the url page in step 1

3. go to https://dceg.cancer.gov

4. Once on DCEG, click on the Launch and Switch Icon. You should see a toggle for Debug and Staging. Change the Staging toggle from Off to On

5. Click back on the DCEG page and hit refresh.

6. You should not be able to test whether the Back to Top is working as expected

7. Once done testing, please hit the Launch DTM icon again and switch the Staging toggle back to the Off position

I can help with this plugin, or if you like, you are free to test this on my machine.

**Comment by alinai** [comment]
Looks good on Chrome and FF. Thanks @markecramer!

**Comment by lburack** [comment]
Thanks for the clear guidance, @markecramer! This passes IA review!

DCEG is now like the other 3 microsites, which as you mentioned in your comment, have an issue with linkback obscuring part of the sticky nav, which this ticket does not fix. #2317 is the ticket for the microsites (we can add DCEG to that list)

**Comment by markecramer** [comment]
I've pushed this fix live. thanks Everyone!
